### ISSUE TITLE
Receive Error message when No Error Exists 

### ISSUE THREAD

**Issue by gshannon00** [ryanhofdotgov/e-QIP-prototype-truetandem#2501] opened 2018-01-25 16:37 UTC
**What did you do?**
Got kicked out of the application and logged back in
*Including steps for recreating it, if applicable.*

**What did you expect to see?**

*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*

**What did you see instead?**
 An error stating there is a problem with a field.
*Include a high-level description of the feature or error here*
The error states If the middle name is an Initial then check the "Initial only' checkbox.  The middle name IS an intitial and the "Initial Only" checkbox IS checked. 
**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*
![image](https://user-images.githubusercontent.com/31284016/35400206-228ae766-01c4-11e8-94b3-a91072e15f42.png)

 - What browser and version are you using?
Google Chrome
 - What operating system?
Windows 7

**Comment by bmallred** [comment] 2018-01-26 14:03
Not seeing this. @floresj can you give it a shot as well?

## Preview

![image](https://user-images.githubusercontent.com/697855/35443070-ae7b48de-0277-11e8-857d-023ed2cfacb6.png)

**Comment by floresj** [comment] 2018-01-26 14:54
@bmallred I'll check it out.

**Comment by bmallred** [comment] 2018-03-23 14:50
Not able to reproduce this and may have been resolved by another issue.

## Initial only
![image](https://user-images.githubusercontent.com/697855/37836005-d86bb6f6-2e87-11e8-989d-cd974291ce06.png)

## Initial only with more than one letter
![image](https://user-images.githubusercontent.com/697855/37836038-e857de8c-2e87-11e8-998e-ea9864c4e9f4.png)

## No middle name
![image](https://user-images.githubusercontent.com/697855/37836020-df33ad18-2e87-11e8-9e80-6e13e17775c9.png)

**Comment by Jay-Neighbours-I72** [comment] 2018-04-09 15:14
Looks like the error message for when Initial only is checked but no text in input is missing.

![screen shot 2018-04-09 at 11 09 43 am](https://user-images.githubusercontent.com/19935974/38506201-2b6eb6d4-3be7-11e8-8674-e1fed2414415.jpg)

**Comment by ryanhofdotgov** [comment] 2018-05-23 23:20
Kamino closed and cloned this issue to 18F/e-QIP-prototype

**Closed by ryanhofdotgov** 2018-05-23 23:20 UTC
Labels: bug, high
