### ISSUE TITLE
Phone number time of day checkboxes overlap content from 1001px-1176px

### ISSUE THREAD

**Issue by lauraponce** [ryanhofdotgov/e-QIP-prototype-truetandem#2692] opened 2018-03-02 19:55 UTC
<img width="538" alt="screen shot 2018-03-02 at 2 46 58 pm" src="https://user-images.githubusercontent.com/21222704/36918977-ac05c0c0-1e29-11e8-9257-f65d310c9472.png">

**Comment by Jay-Neighbours-I72** [comment] 2018-03-08 14:51
Duplicate of #2429

**Closed** 2018-05-23 23:12 UTC
Labels: bug, duplicate, medium
